#+title: Sql As Data Analysis Volapük Part 2
#+date: <2026-07-29 17:53>
#+description:
#+filetags: data sql language todo

4 years ago I wrote a [[file:sql-as-data-analysis-volapuk.org][small note on SQL]], and oh boy things have changed (alas, russia's war in Ukraine hasn't changed that much!):

1. Apache Druid moves from SQL to [[https://druid.apache.org/docs/latest/querying/][its own custom JSON-based native query language]] (so my starting idea didn't hold for too long).
2. Magnificent [[https://duckdb.org][DuckDB]] appeared, removing both most of the other locally-installed DBs, and also providing lots of analytical possibilities to python or even PostgreSQL.
3. Speaking of the beast, PostgreSQL with its extensions for everything got quite a traction.
4. I have lots of books on SQL (mostly quickly scanned through, not read deep enough as they all have to be read): The Art of PostgreSQL by Dimitri Fontaine, DuckDB in Action from Manning, even SQL Queries for Mere Mortals by John L. Viescas. Each of those waits for the note in future.

Alas, I'm not working with Apache Druid anymore, at least for now. But it seems that it's still long until we see the dawn of SQL (also LLMs are writing it beautifully and people are kinda accostumed to not reading it properly).
