#+title: Привіт, чудовий світе
#+date: <2022-10-08 23:04>
#+description:
#+filetags: admin migration war

* WHO:
My name is Volodymyr Anokhin and this is my blog. You may know me as VLNN (mostly at [[https://github.com/vlnn][vlnn@github.com)]]. I'm Ukrainian and that's why instead of "Hello, wonderful world" you may see some Cyrillics in the title of this record.

* WHAT:
This is another try to set up minimalistic mostly technical blog. I plan to write things about my current projects which are mostly software-related at the moment. I was working as a Radio Engineer, as an Engineering Manager, and now I am a software developer. Somehow I always have chosen less-popular programming languages, and so I was writing production code in J, FORTH and APL. Now I moved a bit to more conventional side of Clojure.

* WHY:
It's not my first try to set up a place to share some technical or not-that-technical stuff across the internet. But somehow all the "social" platforms tend to become a social burden, and "technical" platforms tend to become more social with time. So I want to create a small piece of the network here, with smaller auditory but much bigger calmness. I'm not even sure that I will enable comments here!

* WHEN:
It's a wartime, joint forces of russia and belorussia are attacking and occupying parts of Ukraine right now. Perhaps not the best time to start a blog! But it's creation is not related to less chances of russia to kill or torture me. This is directly related to my plans to make everything I have to do during the war: support Ukrainian army, spend money for Ukrainian goods, and also represent Ukraine in every possible way. We are here. Some of us are still alive. We're kicking.

And we'll never forgive russians for what they did.
