#+title: #+title: Antiprogress of the Dropbox
#+date: <2023-01-24 14:44>
#+description:
#+filetags: getting-older,dropbox,web

Not that long time ago (or was it long time? 10 years ago or so?) Dropbox was the new kind of the services -- very simple, very cheap, very direct kind of service. You want to share the photo or your hipster todo.txt, you put it in a special folder and that's it: it will be delivered automatically to everybody whom you informed the link, or to every PC where Dropbox is running under your creds. That's it! Super easy, super cool!

I just used current version of Dropbox app for Android, and it is just terrifyingly awful. For starters, it has tutorial wizards that break my needs; I want to press a button, but it is covered with a text cloud of a tutorial. Next, I want to download some video files to my android device: there are buttons "Sync", "Make available offline" and "Save to Device" -- and also "Duplicate". Next, it asks to access my photos and my camera. And moreover, it shares the names of people who have access to the folder to anybody who has it already.

I can't even...

I understand Syncthing could be infuriatingly complex, but at least it does one thing, and does it good.
